# Generated by Django 2.2.6 on 2020-04-08 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('codigo_ciclo', models.IntegerField(primary_key=True, serialize=False)),
                ('ciclo_lectivo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codigo_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('carnet_alumno', models.CharField(max_length=7)),
                ('nombre_alumno', models.CharField(max_length=200)),
                ('sexo_alumno', models.CharField(max_length=1)),
                ('telefono_alumno', models.IntegerField()),
                ('correo_alumno', models.CharField(max_length=50)),
                ('direccion_alumno', models.CharField(max_length=50)),
                ('carrera_alumno', models.CharField(max_length=50)),
                ('porc_carr_apro', models.IntegerField()),
                ('unidades_valorativas', models.IntegerField()),
                ('experiencias_alumno', models.CharField(max_length=50)),
                ('horas_semana', models.IntegerField()),
                ('dias_semana', models.IntegerField()),
                ('propuesta_entidad', models.CharField(max_length=50)),
                ('propuesta_modalidad', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('estado_expediente', models.CharField(max_length=10)),
                ('motivo', models.CharField(max_length=50, null=True)),
                ('observaciones', models.CharField(max_length=50, null=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Ciclo')),
            ],
        ),
    ]
