# Generated by Django 3.1.1 on 2020-11-12 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasSociales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField()),
                ('hora_entrada', models.DateTimeField()),
                ('actividad_realizada', models.CharField(max_length=50)),
                ('hora_salida', models.DateTimeField()),
                ('horas_realizadas', models.DateTimeField()),
                ('carnet_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.estudiante')),
            ],
        ),
    ]
