# Generated by Django 2.2.16 on 2020-09-20 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivosEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(blank=True, null=True, upload_to='Documentos')),
                ('carnet_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Estudiante')),
            ],
        ),
    ]
