# Generated by Django 2.2.6 on 2021-01-06 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('correlativo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(max_length=50)),
                ('carnet_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Estudiante')),
            ],
        ),
    ]
