# Generated by Django 3.1.1 on 2020-11-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_horassociales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horassociales',
            name='hora_entrada',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='horassociales',
            name='hora_salida',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='horassociales',
            name='horas_realizadas',
            field=models.CharField(max_length=1),
        ),
    ]
