# Generated by Django 2.2.16 on 2020-09-23 03:05

import apps.app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_archivosestudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivosestudiante',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to=apps.app1.models.crear_subcarpeta),
        ),
    ]
